name: Build project
on: 
  push:
    branches: 
      - main
  merge_group:
    type: [checks_requested]
  
jobs:
  buildForAndroidPlatforms:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android
          restore-keys: Library-
      - uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
      - uses: actions/upload-artifact@v3
        with:
          name: Build-Android
          path: build/Android